name = "proxy-anorsi"             # любое уникальное имя воркера
main = "src/worker.js"            # путь до скрипта
compatibility_date = "2025-06-19" # сегодняшняя дата (YYYY-MM-DD)

# (необязательно) сразу привяжем роут
routes = [
  { pattern = "anorsi.msk.ru/*", zone_name = "anorsi.msk.ru" }
]
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# если нужно окружение (env)
# [env.staging]
# routes = [ { pattern = "beta.anorsi.msk.ru/*", zone_name = "anorsi.msk.ru" } ]
